In [5]:
l=[23245, 27, 546, 215, -1234]

In [6]:
l

[23245, 27, 546, 215, -1234]

In [7]:
import numpy as np

In [8]:
a=np.array(l)

In [9]:
a

array([23245,    27,   546,   215, -1234])

In [10]:
b=np.array([12, 455, 63.3, True, "abc"])

In [11]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [12]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [13]:
l.pop()

-1234

In [14]:
l

[23245, 27, 546, 215]

In [15]:
a.mean()

4559.8

In [16]:
a

array([23245,    27,   546,   215, -1234])

In [17]:
l

[23245, 27, 546, 215]

In [18]:
b[:]=111

In [19]:
b

array(['111', '111', '111', '111', '111'], dtype='<U32')

In [20]:
a

array([23245,    27,   546,   215, -1234])

In [21]:
c=a.copy()

In [22]:
c

array([23245,    27,   546,   215, -1234])

In [23]:
c[0] = 0

In [24]:
c

array([    0,    27,   546,   215, -1234])